Repository trouni/predictor-vue, pull requests merged in 2021-06, with the labels that each got.

#59 New leaderboard
  src/api/repositories/leaderboards.js
  src/components/LeaderboardAction.vue
  src/components/LeaderboardActions.vue
  src/components/ShareButton.vue
  src/store/modules/leaderboards.js
  src/styles/_colors.scss
  src/views/LeaderboardNew.vue
  src/views/Leaderboards.vue
  src/views/layouts/DefaultLayout.vue
Labels: enhancement

#67 Fix/join routes
  src/components/Header.vue
  src/components/LeaderboardSubHeader.vue
  src/router/routes.js
  src/store/modules/leaderboards.js
  src/views/Leaderboards.vue
  src/views/layouts/DefaultLayout.vue
Labels: bug

#63 A user can update their display name
  src/api/repositories/users.js
  src/store/modules/users.js
  src/views/UserProfile.vue
Labels: enhancement

#70 Fix: Set default competition to id=1
  src/router/routes.js
  src/views/Leaderboards.vue
  src/views/Matches.vue
Labels: bug

#71 Fix animation when making prediction
  src/components/MatchCard.vue
Labels: bug

#64 Sign in/up Header and Labels
  src/router/routes.js
  src/views/Login.vue
Labels: enhancement

#73 Display match groupings
  src/components/MatchesGrouping.vue
  src/views/Matches.vue
Labels: enhancement

#74 Tinder like swipe
  package.json
  src/App.vue
  src/assets/ball.jpg
  src/components/PredictionSwiper.vue
  src/components/PredictionSwiperCard.vue
  src/components/PredictionSwiperStatus.vue
  src/router/routes.js
  src/utils/helpers.js
  src/views/Matches.vue
  src/views/PredictionsNew.vue
  tailwind.config.js
  yarn.lock
Labels: enhancement

#75 Scroll content in default layout
  src/views/layouts/DefaultLayout.vue
Labels: enhancement

#80 Add Sentry config
  package.json
  src/components/PredictionSwiper.vue
  src/main.js
  yarn.lock
Labels: enhancement

#82 Fix/competition routes
  src/api/repositories/competitions.js
  src/components/FooterNav.vue
  src/components/PredictionSwiper.vue
  src/components/PredictionSwiperStatus.vue
  src/router/index.js
  src/router/routes.js
  src/store/modules/auth.js
  src/store/modules/competitions.js
  src/store/modules/leaderboards.js
  src/store/modules/matches.js
  src/utils/helpers.js
  src/views/Competition.vue
  src/views/Home.vue
  src/views/LeaderboardNew.vue
  src/views/Leaderboards.vue
  src/views/Matches.vue
  src/views/PredictionsNew.vue
Labels: bug, enhancement

#94 Swipe to change leaderboards
  src/components/LeaderboardSubHeader.vue
  src/components/MatchesSubHeader.vue
  src/store/modules/leaderboards.js
  src/views/layouts/DefaultLayout.vue
Labels: enhancement

#72 Use arrow keys to switch leaderboard
  src/components/LeaderboardSubHeader.vue
Labels: enhancement

#93 Style swiper and fix various styling issues
  src/App.vue
  src/assets/lightning.png
  src/components/MatchCard.vue
  src/components/PredictionSwiper.vue
  src/components/PredictionSwiperCard.vue
  src/components/PredictionSwiperStatus.vue
  src/router/routes.js
  src/utils/helpers.js
  src/utils/request.js
  src/views/Matches.vue
  src/views/PredictionsNew.vue
  tailwind.config.js
Labels: bug, enhancement

#95 Add loading bouncing ball
  src/components/PredictionSwiperStatus.vue
  src/components/_BaseSpinner.vue
  src/views/Competition.vue
  src/views/Leaderboards.vue
  src/views/Login.vue
  src/views/Matches.vue
  src/views/PredictionsNew.vue
  src/views/UserProfile.vue
  src/views/layouts/DefaultLayout.vue
  tailwind.config.js
Labels: enhancement

#101 Add font
  src/styles/_fonts.scss
Labels: enhancement

#103 Caching - Load data from store before fetching
  src/components/PredictionSwiper.vue
  src/store/modules/matches.js
  src/views/Leaderboards.vue
  src/views/Matches.vue
  src/views/PredictionsNew.vue
Labels: enhancement

#120 changed share->invite and add->new
  src/components/LeaderboardActions.vue
  src/components/ShareButton.vue
Labels: enhancement

#119 sorting users by points
  src/components/LeaderboardCard.vue
Labels: bug

#122 made everything bigger for the landing page
  src/components/HomeStep.vue
  src/views/Home.vue
Labels: enhancement

#121 added the octopus as the logo on the topnav
  src/assets/logo.png
  src/components/TopNav.vue
Labels: enhancement

#124 Remove membership
  src/api/repositories/leaderboards.js
  src/components/ConfirmDelete.vue
  src/components/LeaderboardAction.vue
  src/components/LeaderboardActions.vue
  src/store/modules/leaderboards.js
Labels: enhancement

#125 Add confirmation + Allow updating of predictions
  src/App.vue
  src/components/ConfirmButton.vue
  src/components/PredictionSwiper.vue
  src/components/PredictionSwiperCard.vue
  src/components/PredictionSwiperStatus.vue
  src/components/UndoButton.vue
  src/components/_BaseIcon.vue
  src/router/routes.js
  src/store/index.js
  src/store/modules/matches.js
  src/views/Matches.vue
  src/views/PredictionsNew.vue
  src/views/layouts/DefaultLayout.vue
  tailwind.config.js
Labels: bug, enhancement

#129 Tweak footer navbar styling
  src/components/FooterNav.vue
  src/components/NavBarRoutes.vue
Labels: enhancement

#130 Fix the team name's display right after pressing confirm
  src/components/PredictionSwiper.vue
  src/components/PredictionSwiperCard.vue
Labels: bug

#135 Feature: show predictions from other users
  src/api/repositories/users.js
  src/components/LeaderboardCard.vue
  src/components/LeaderboardRanking.vue
  src/components/MatchCard.vue
  src/components/MatchesGrouping.vue
  src/components/_BaseLink.vue
  src/store/modules/matches.js
  src/store/modules/users.js
  src/utils/helpers.js
  src/views/Matches.vue
Labels: enhancement

#134 small check feedback on when a username gets update
  src/views/UserProfile.vue
Labels: enhancement

#136 Tweak button style
  src/components/_BaseButton.vue
  tailwind.config.js
Labels: enhancement

#150 removed 'vs.' and centered the DRAW action
  src/components/MatchCard.vue
Labels: enhancement

#149 Profile fetch user
  src/views/UserProfile.vue
Labels: bug

#148 Prediction Indicator
  src/components/CornerPoints.vue
  src/components/MatchCard.vue
  src/components/PredictionChoiceTeam.vue
Labels: enhancement

#152 removed the useless navbar color
  src/components/TopNav.vue
Labels: enhancement

#151 Match tabs
  src/components/MatchTab.vue
  src/components/MatchesGrouping.vue
  src/views/Matches.vue
Labels: enhancement

#155 Added a div to center the content on desktop
  src/views/layouts/DefaultLayout.vue
Labels: enhancement

#156 navbar bg-color && grayed out icon
  src/components/NavBarRoutes.vue
  src/components/TopNav.vue
  src/views/Home.vue
Labels: bug

#157 Leadberboard tabs
  src/components/LeaderboardTabs.vue
  src/views/Leaderboards.vue
Labels: enhancement

#158 replaced home button with back button when logged in
  src/components/FooterNav.vue
Labels: enhancement

#159 Fix/ranking number
  src/components/LeaderboardCard.vue
Labels: enhancement

#160 not sure it's necessary to have users navigate between stages
  src/components/MatchesSubHeader.vue
Labels: enhancement

#161 added location to the match
  src/components/PredictionSwiper.vue
Labels: enhancement

#162 Disable draw
  src/components/MatchCard.vue
  src/components/PredictionSwiperCard.vue
Labels: enhancement
