Repository trouni/predictor-vue, pull requests merged in 2022-12, with the labels that each got.

#216 Add snap scroll switching of leaderboards
  src/components/AnimatedArrow.vue
  src/components/LeaderboardRankingsCard.vue
  src/components/LeaderboardSubHeader.vue
  src/store/modules/leaderboards.js
  src/utils/request.js
  src/views/ForgotPassword.vue
  src/views/LeaderboardNew.vue
  src/views/Login.vue
  src/views/Predict.vue
  src/views/Predictions.vue
  src/views/Rankings.vue
  src/views/ResetPassword.vue
  src/views/Results.vue
  src/views/UserProfile.vue
  src/views/layouts/DefaultLayout.vue
  src/views/layouts/SnapNavigationLayout.vue
Labels: enhancement

#219 Fix/hint tip
  src/components/PredictionHint.vue
  src/components/PredictionSwiper.vue
Labels: bug

#232 shows red color for incorrect choice
  src/components/MatchPredictions.vue
  src/components/ResultCard.vue
Labels: enhancement

#234 Fixing various minor issues
  src/components/FooterNav.vue
  src/components/LeaderboardAction.vue
  src/components/PredictionSwiper.vue
  src/components/SwipeTutorial.vue
  src/router/index.js
  src/store/modules/auth.js
  src/views/LeaderboardNew.vue
  src/views/Predict.vue
  src/views/Results.vue
  src/views/layouts/SnapNavigationLayout.vue
Labels: bug, enhancement

#239 displaying extra time and penalty scores if there
  src/components/PredictionChoiceTeam.vue
  src/components/TeamBadge.vue
Labels: bug
