Repository trouni/predictor-vue, pull requests merged in 2022-11, with the labels that each got.

#184 zoomed into center of flag
  src/components/TeamBadge.vue
Labels: enhancement

#188 Fix home page background
  src/views/Home.vue
Labels: bug

#187 Update sass dependencies for M1 Mac
  package.json
  yarn.lock
Labels: dependencies

#181 hard coded last competition to use World Cup
  src/store/modules/competitions.js
Labels: enhancement

#138 starting with register if you're not logged in on a join link
  src/views/Login.vue
Labels: enhancement

#195 Update leaderboard style
  .env.development
  src/components/LeaderboardCard.vue
  src/components/LeaderboardRanking.vue
  src/components/LeaderboardSubHeader.vue
  src/store/modules/competitions.js
  src/store/modules/leaderboards.js
  src/views/Matches.vue
  src/views/UserProfile.vue
  src/views/layouts/DefaultLayout.vue
Labels: enhancement

#203 Unhid upload btn
  src/views/UserProfile.vue
Labels: bug

#198 changed incorrect to wrong
  src/components/TeamBadge.vue
Labels: bug

#202 added possible points to the user total points
  src/components/LeaderboardRanking.vue
Labels: enhancement
